apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

patches:
  - target:
      version: v1
      kind: Service
      name: welcome-php
    patch: |-
      - op: replace
        path: /spec/ports/targetPort
        value: "8081"

